site_name: Music Genre Classification
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.top

nav:
  - Final Report: ./final_report.md
  - Project Summary: ./project_summary.md
  - Usage:
      - Download: ./experiments/download.md
      - Convert: ./experiments/convert.md
      - Training: ./experiments/1_training.md
  - Experiments:
      - Data: ./experiments/0_data.md
      - Training Dry Run: ./experiments/1_training.md
      - MusicRecNet: ./experiments/2_musicrecnet_sgd.md
      - ResNet: ./experiments/2_resnet_decay.md
      - MgcNet: ./experiments/2_mynet.md
      - Full Experiment: ./experiments/training.md
      - Spectrogram: ./experiments/spectrogram.md
      - Final: ./experiments/final.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences