site_name: Music Genre Classification
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.top

nav:
  - Data: ./experiments/0_data.md
  - Training: ./experiments/1_training.md
  - MusicRecnet: ./experiments/2_musicrecnet_sgd.md
  - Experiment: ./experiments/3_training.md

plugins:
  mkdocs-jupyter:
    theme: dark

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences