name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - run: pip install mkdocs-material jupyter
      - run: python -m jupyter nbconvert --output-dir="./docs/experiments" --to markdown "./experiments/*.ipynb"
      - run: mkdocs gh-deploy --force