name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - run: pip install mkdocs jupyter
      - run: python -m jupyter nbconvert --output-dir="./docs/experiments" --to markdown "./experiments/*.ipynb"
      - run: mkdocs gh-deploy --force --clean --verbose